### DISCUSSION TITLE
Patched P2P drivers for multi-gpu

### DISCUSSION THREAD

**Discussion by aaronlockhartdev** [noonghunna/club-3090#70] [General]
I know that NCCL_P2P_DISABLE=1 is set on all non-NVLink configurations, but I was wondering if any thought has been given to possible performance gains by enabling P2P with a patched, P2P-enabled driver like [aikitoria/open-gpu-kernel-modules](https://github.com/aikitoria/open-gpu-kernel-modules). I believe VLLM can be pretty easily monkey-patched to assume P2P is supported, since it doesn't recognize the patched driver. 

Has this already been tested/found to provide no significant boost? If not, I'm happy to investigate further/run some benchmarks on my rig.

**Comment by noonghunna** [comment]
@aaronlockhartdev — yes please, this is **exactly** the experiment we don't have data on. Hasn't been tested on club-3090 yet; would be the **first patched-driver P2P data point** on our matrix.

The reason it's interesting: @JusefPol's actual NVLink data on `dual.yml` shows **+58% narr / +56% code** vs the `NCCL_P2P_DISABLE=1` PCIe-only baseline (108.81 / 138.55 vs 69 / 89). That gap is the NCCL allreduce-latency floor on TP=2. If aikitoria's patched driver gets a similar effect on consumer-non-NVLink rigs, that's **massive** for the ~95% of dual-3090 owners who don't have NVLink bridges. Even half the gain (+25-30%) would be a big deal.

If you have cycles to bench, here's the cleanest experimental shape we'd want:

## Reproducer

```bash
cd ~/club-3090 && git pull
bash scripts/setup.sh qwen3.6-27b   # downloads weights + Genesis if needed
```

**Bench A — PCIe baseline** (control, NCCL_P2P_DISABLE=1):
```bash
bash scripts/switch.sh vllm/dual
bash scripts/bench.sh                                    # canonical narr + code (~5 min)
SOAK_MODE=continuous bash scripts/soak-test.sh           # 25 min, optional
```
Expected: ~69 narr / ~89 code (per @noonghunna 2026-04-29) or ~89 narr / ~117 code (per @lolren on v7.72.2 image, [disc #18](https://github.com/noonghunna/club-3090/discussions/18#discussioncomment-16820303)).

**Bench B — patched-driver P2P** (test):
1. Install [aikitoria/open-gpu-kernel-modules](https://github.com/aikitoria/open-gpu-kernel-modules) per their instructions
2. Verify P2P via `nvidia-smi topo -p2p r` — should show `OK` between GPU 0 and GPU 1 (vs `CNS Chipset Not Supported` on stock driver)
3. In `models/qwen3.6-27b/vllm/compose/docker-compose.dual.yml`, change:
   ```yaml
   - NCCL_P2P_DISABLE=1
   ```
   to:
   ```yaml
   - NCCL_P2P_LEVEL=PIX        # or NCCL_P2P_LEVEL=PHB depending on your topology
   ```
   (whatever the patched driver actually advertises — check `nvidia-smi topo -m`)
4. Optionally also remove `--disable-custom-all-reduce` if P2P is recognized end-to-end (vLLM's custom kernel may now pay off the way NVLink does)
5. `bash scripts/switch.sh vllm/dual` and re-bench

## What we'd learn

- **Does NCCL actually use the P2P path** with the patched driver? (some drivers report capability but the PCIe lanes don't actually do peer transfers)
- **What's the practical TPS gain** vs unpatched? Bracketed by JusefPol's NVLink result on the high end (+56%) and "no measurable change" on the low end
- **Does custom-all-reduce work** with patched-driver P2P? (NVLink enables it; raw PCIe disables it; patched-driver-PCIe is the unknown middle)

## Risk callouts

- aikitoria's modules require kernel module signing or `--allow-unauthenticated` in some distros — not a club-3090 concern, but flag it
- Driver replacement is a system-level change; we'd want a clean rollback path (`dkms remove` etc.) documented
- vLLM monkey-patch you mentioned: shouldn't be needed if NCCL_P2P_LEVEL is set + the patched driver advertises P2P-capable. If it IS needed, the diff is something we'd want to understand before recommending.

## How to share the data

Open a [Numbers from your rig](https://github.com/noonghunna/club-3090/issues/new?template=numbers-from-your-rig.yml) issue with:
- `bash scripts/report.sh --full` output
- `nvidia-smi topo -p2p r` before/after the patched driver
- A/B canonical bench numbers

We'll add as a row in BENCHMARKS.md attributed to your rig + write up the methodology in a learnings file. If the gain is real, this becomes a documented path for non-NVLink dual-3090 owners — genuine value-add for the matrix.

Genuinely thanks for the offer. Looking forward to the numbers.

**Reply by aaronlockhartdev** [reply]
Benchmark posted [here](https://github.com/noonghunna/club-3090/issues/91). Small TPS gain. I didn't see the comment about not needing the monkey patch, I'll test that and other configurations when I'm able.

**Reply by aaronlockhartdev** [reply]
Not sure why I got such higher baselines than the posted ones for `dual`, is this due to an update upstream?

**Comment by noonghunna** [comment]
**Answer arrived** — @aaronlockhartdev ran the controlled A/B in [issue #91](https://github.com/noonghunna/club-3090/issues/91). Net: patched P2P drivers give **+2% narr / +9% code** on his 2× 3090 + dual.yml setup vs unpatched baseline. Compared to NVLink hardware (+15% / +15%), patched P2P captures ~60% of the code gain but only ~13% of the narr gain.

The asymmetry is the genuinely useful finding — code workloads spend more cycles in spec-decode K+1 verify (cross-card matmul, bandwidth-sensitive); narrative decode is more sequential per-token. Full diagnostic + tradeoff framing in [issue #91](https://github.com/noonghunna/club-3090/issues/91#issuecomment-4393293058). BENCHMARKS row landed at [`4eea837`](https://github.com/noonghunna/club-3090/commit/4eea837).

**Comment by aaronlockhartdev** [comment]
Results for `dual-dflash-noviz` posted [here](https://github.com/noonghunna/club-3090/issues/95). Much better speedup than for `dual`, and patching VLLM in a custom image shown to be unnecessary. I couldn't reopen my previous issue. It occurs to me that it might be worth it to further A/B test having P2P enabled in the container with and without the patched driver–I can do that in the future.

**Comment by noonghunna** [comment]
Thanks @aaronlockhartdev — the [#95 result](https://github.com/noonghunna/club-3090/issues/95) closes this discussion's open question more thoroughly than I expected. **Two takeaways worth surfacing for anyone watching this thread:**

| Compose shape | Patched-P2P lift |
|---|---:|
| `dual.yml` (no spec-decode) | +2% / +9% |
| `dual-dflash-noviz` (DFlash N=5) | **+22% / +19%** |

**The lift scales with spec-decode depth** because the K+1 verify pattern is heavily cross-card matmul. Patched P2P recovers more of that bandwidth than `dual.yml`'s pure-decode pattern exposes.

**`NCCL_P2P_LEVEL=PHB` alone with the default vLLM image is sufficient** — the vLLM `cuda.py` patch (the part that actually requires a custom Docker image) turns out to be unnecessary. That's a meaningful simplification of the recommendation: only the kernel module patch carries weight; the env var unlocks it.

## On the future custom_all_reduce A/B

Your follow-up suggestion (in-container P2P with vs without the patched driver) is a high-value 4-row matrix:

| custom_all_reduce | NCCL_P2P_LEVEL | Expected | What it tells us |
|---|---|---|---|
| OFF | PHB | (your earlier `dual.yml` baseline) | Reference |
| OFF | NVL | ? | Can in-container P2P kick in independently of the env var? |
| ON | PHB | (this disc's `dual-dflash-noviz` row) | Reference |
| ON | NVL | ? | Do they stack, or is one masking the other? |

If you run it, that's the data that informs **the canonical recommendation in `docs/HARDWARE.md` for everyone with the patched kernel module installed**. Right now the doc says "set `NCCL_P2P_LEVEL=PHB`"; the 4-row matrix tells us whether `custom_all_reduce` should be on or off by default.

Not asking — flagging it as the natural next data point. Whenever you have cycles. The new `--bench-runs 3` flag on `power-cap-sweep.sh` is the right tool for this kind of A/B if you want median'd numbers.

I'll close this discussion topic-wise (the original question is answered), but happy to keep it open if you'd rather run the future A/B in this thread vs filing a new one.
