### ISSUE TITLE
[bug] launch script handling of ports and container names is broken

### ISSUE THREAD

**Issue by AlexCPU** [noonghunna/club-3090#20]
### What happened?

I started launch script, selected dual 3090's and option 1.  It starts the stack correctly, waiting for the models endpoint on port 8010 to show up, which it does.  Then it runs on to the functional checks, where it's now using port 8020 (which doesn't work), and checking the wrong docker container name.  It's checking for `vllm-qwen36-27b` when the container is named `vllm-qwen36-27b-dual`

### Steps to reproduce

```bash
bash scripts/setup.sh qwen3.6-27b
bash scripts/launch.sh
```

### docker logs (last 100 lines)

```text
(Worker_TP0 pid=82) INFO 05-01 11:05:17 [default_loader.py:384] Loading weights took 12.72 seconds
(Worker_TP0 pid=82) INFO 05-01 11:05:17 [gpu_model_runner.py:4790] Loading drafter model...
(Worker_TP0 pid=82) INFO 05-01 11:05:17 [weight_utils.py:904] Filesystem type for checkpoints: EXT4. Checkpoint size: 17.69 GiB. Available RAM: 56.26 GiB.
Loading safetensors checkpoint shards:   0% Completed | 0/11 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  73% Completed | 8/11 [00:00<00:00, 11.31it/s]
Loading safetensors checkpoint shards:  91% Completed | 10/11 [00:01<00:00,  6.20it/s]
Loading safetensors checkpoint shards: 100% Completed | 11/11 [00:01<00:00,  5.70it/s]
Loading safetensors checkpoint shards: 100% Completed | 11/11 [00:01<00:00,  6.51it/s]
(Worker_TP0 pid=82)
(Worker_TP0 pid=82) INFO 05-01 11:05:19 [default_loader.py:384] Loading weights took 1.70 seconds
(Worker_TP1 pid=83) INFO 05-01 11:05:20 [llm_base_proposer.py:1433] Detected MTP model. Sharing target model embedding weights with the draft model.
(Worker_TP1 pid=83) INFO 05-01 11:05:20 [llm_base_proposer.py:1489] Detected MTP model. Sharing target model lm_head weights with the draft model.
(Worker_TP0 pid=82) INFO 05-01 11:05:20 [llm_base_proposer.py:1433] Detected MTP model. Sharing target model embedding weights with the draft model.
(Worker_TP0 pid=82) INFO 05-01 11:05:20 [llm_base_proposer.py:1489] Detected MTP model. Sharing target model lm_head weights with the draft model.
(Worker_TP1 pid=83) INFO 05-01 11:05:21 [interface.py:606] Setting attention block size to 1600 tokens to ensure that attention page size is >= mamba page size.
(Worker_TP1 pid=83) INFO 05-01 11:05:21 [interface.py:630] Padding mamba page size by 0.25% to ensure that mamba page size and attention page size are exactly equal.
(Worker_TP0 pid=82) INFO 05-01 11:05:21 [gpu_model_runner.py:4868] Model loading took 8.93 GiB memory and 16.423791 seconds
(Worker_TP0 pid=82) INFO 05-01 11:05:21 [interface.py:606] Setting attention block size to 1600 tokens to ensure that attention page size is >= mamba page size.
(Worker_TP0 pid=82) INFO 05-01 11:05:21 [interface.py:630] Padding mamba page size by 0.25% to ensure that mamba page size and attention page size are exactly equal.
(Worker_TP0 pid=82) INFO 05-01 11:05:21 [gpu_model_runner.py:5809] Encoder cache will be initialized with a budget of 16384 tokens, and profiled with 1 image items of the maximum feature size.
(Worker_TP0 pid=82) INFO 05-01 11:05:32 [backends.py:1069] Using cache directory: /root/.cache/vllm/torch_compile_cache/eecc6417d1/rank_0_0/backbone for vLLM's torch.compile
(Worker_TP0 pid=82) INFO 05-01 11:05:32 [backends.py:1128] Dynamo bytecode transform time: 8.92 s
(Worker_TP0 pid=82) INFO 05-01 11:05:34 [backends.py:376] Cache the graph of compile range (1, 8192) for later use
(Worker_TP0 pid=82) INFO 05-01 11:05:57 [backends.py:391] Compiling a graph for compile range (1, 8192) takes 25.19 s
(Worker_TP0 pid=82) INFO 05-01 11:06:20 [decorators.py:668] saved AOT compiled function to /root/.cache/vllm/torch_compile_cache/torch_aot_compile/870372bcba8b6248b42b3ca0c758a47b7c22322e47b6a9e03bb86a0752cae746/rank_0_0/model
(Worker_TP0 pid=82) INFO 05-01 11:06:20 [monitor.py:53] torch.compile took 57.11 s in total
(EngineCore pid=73) INFO 05-01 11:06:22 [shm_broadcast.py:681] No available shared memory broadcast block found in 60 seconds. This typically happens when some processes are hanging or doing some time-consuming work (e.g. compilation, weight/kv cache quantization).
(Worker_TP0 pid=82) INFO 05-01 11:07:11 [monitor.py:81] Initial profiling/warmup run took 51.33 s
(Worker_TP0 pid=82) INFO 05-01 11:07:12 [backends.py:1069] Using cache directory: /root/.cache/vllm/torch_compile_cache/eecc6417d1/rank_0_0/eagle_head for vLLM's torch.compile
(Worker_TP0 pid=82) INFO 05-01 11:07:12 [backends.py:1128] Dynamo bytecode transform time: 0.45 s
(Worker_TP0 pid=82) INFO 05-01 11:07:18 [backends.py:391] Compiling a graph for compile range (1, 8192) takes 6.54 s
(Worker_TP0 pid=82) INFO 05-01 11:07:19 [decorators.py:668] saved AOT compiled function to /root/.cache/vllm/torch_compile_cache/torch_aot_compile/1e62191a7680b650dfe89c97d3808dd03946883988b4248764fd55557e43cc70/rank_0_0/model
(Worker_TP0 pid=82) INFO 05-01 11:07:19 [monitor.py:53] torch.compile took 7.26 s in total
(Worker_TP0 pid=82) INFO 05-01 11:07:19 [monitor.py:81] Initial profiling/warmup run took 0.76 s
(Worker_TP0 pid=82) WARNING 05-01 11:07:21 [kv_cache_utils.py:1070] Add 3 padding layers, may waste at most 6.25% KV cache memory
(Worker_TP0 pid=82) WARNING 05-01 11:07:21 [compilation.py:1370] CUDAGraphMode.FULL_AND_PIECEWISE is not supported with spec-decode for attention backend FlashInferBackend (support: AttentionCGSupport.UNIFORM_SINGLE_TOKEN_DECODE); setting cudagraph_mode=PIECEWISE
(Worker_TP1 pid=83) WARNING 05-01 11:07:21 [kv_cache_utils.py:1070] Add 3 padding layers, may waste at most 6.25% KV cache memory
(Worker_TP1 pid=83) WARNING 05-01 11:07:21 [compilation.py:1370] CUDAGraphMode.FULL_AND_PIECEWISE is not supported with spec-decode for attention backend FlashInferBackend (support: AttentionCGSupport.UNIFORM_SINGLE_TOKEN_DECODE); setting cudagraph_mode=PIECEWISE
(Worker_TP0 pid=82) INFO 05-01 11:07:21 [gpu_model_runner.py:5938] Profiling CUDA graph memory: PIECEWISE=5 (largest=16)
(Worker_TP1 pid=83) INFO 05-01 11:07:21 [gpu_model_runner.py:5938] Profiling CUDA graph memory: PIECEWISE=5 (largest=16)
(EngineCore pid=73) INFO 05-01 11:07:22 [shm_broadcast.py:681] No available shared memory broadcast block found in 60 seconds. This typically happens when some processes are hanging or doing some time-consuming work (e.g. compilation, weight/kv cache quantization).
(Worker_TP1 pid=83) INFO 05-01 11:07:22 [gpu_model_runner.py:6017] Estimated CUDA graph memory: 0.13 GiB total
(Worker_TP0 pid=82) INFO 05-01 11:07:22 [gpu_model_runner.py:6017] Estimated CUDA graph memory: 0.13 GiB total
(Worker_TP1 pid=83) INFO 05-01 11:07:23 [gpu_worker.py:455] CUDA graph memory profiling is enabled (default since v0.21.0). The current --gpu-memory-utilization=0.9200 is equivalent to --gpu-memory-utilization=0.9145 without CUDA graph memory profiling. To maintain the same effective KV cache size as before, increase --gpu-memory-utilization to 0.9255. To disable, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=0.
(Worker_TP0 pid=82) INFO 05-01 11:07:23 [gpu_worker.py:440] Available KV cache memory: 11.48 GiB
(Worker_TP0 pid=82) INFO 05-01 11:07:23 [gpu_worker.py:455] CUDA graph memory profiling is enabled (default since v0.21.0). The current --gpu-memory-utilization=0.9200 is equivalent to --gpu-memory-utilization=0.9145 without CUDA graph memory profiling. To maintain the same effective KV cache size as before, increase --gpu-memory-utilization to 0.9255. To disable, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=0.
(EngineCore pid=73) WARNING 05-01 11:07:23 [kv_cache_utils.py:1070] Add 3 padding layers, may waste at most 6.25% KV cache memory
(EngineCore pid=73) INFO 05-01 11:07:23 [kv_cache_utils.py:1337] GPU KV cache size: 176,000 tokens
(EngineCore pid=73) INFO 05-01 11:07:23 [kv_cache_utils.py:1342] Maximum concurrency for 262,144 tokens per request: 2.47x
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 5/5 [00:00<00:00, 10.95it/s]
(Worker_TP1 pid=83) INFO 05-01 11:07:24 [gpu_worker.py:599] CUDA graph pool memory: 0.1 GiB (actual), 0.13 GiB (estimated), difference: 0.03 GiB (33.3%).
(Worker_TP0 pid=82) INFO 05-01 11:07:24 [gpu_model_runner.py:6108] Graph capturing finished in 1 secs, took -0.12 GiB
(Worker_TP0 pid=82) INFO 05-01 11:07:24 [gpu_worker.py:599] CUDA graph pool memory: -0.12 GiB (actual), 0.13 GiB (estimated), difference: 0.25 GiB (26668236800.0%).
(EngineCore pid=73) INFO 05-01 11:07:24 [core.py:298] init engine (profile, create kv cache, warmup model) took 123.62 s (compilation: 64.98 s)
(EngineCore pid=73) INFO 05-01 11:07:26 [nixl_utils.py:32] NIXL is available
(EngineCore pid=73) [transformers] `Qwen2VLImageProcessorFast` is deprecated. The `Fast` suffix for image processors has been removed; use `Qwen2VLImageProcessor` instead.
(EngineCore pid=73) [transformers] The `use_fast` parameter is deprecated and will be removed in a future version. Use `backend="torchvision"` instead of `use_fast=True`, or `backend="pil"` instead of `use_fast=False`.
(EngineCore pid=73) WARNING 05-01 11:07:30 [interface.py:686] Using 'pin_memory=False' as WSL is detected. This may slow down the performance.
(EngineCore pid=73) INFO 05-01 11:07:30 [vllm.py:840] Asynchronous scheduling is enabled.
(EngineCore pid=73) INFO 05-01 11:07:30 [kernel.py:203] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'])
(APIServer pid=1) INFO 05-01 11:07:30 [api_server.py:598] Supported tasks: ['generate']
(APIServer pid=1) INFO 05-01 11:07:31 [parser_manager.py:202] "auto" tool choice has been enabled.
(APIServer pid=1) WARNING 05-01 11:07:31 [model.py:1433] Default vLLM sampling parameters have been overridden by the model's `generation_config.json`: `{'temperature': 1.0, 'top_k': 20, 'top_p': 0.95}`. If this is not intended, please relaunch vLLM instance with `--generation-config vllm`.
(APIServer pid=1) INFO 05-01 11:07:32 [hf.py:314] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.
(APIServer pid=1) INFO 05-01 11:07:37 [base.py:233] Multi-modal warmup completed in 5.461s
(APIServer pid=1) INFO 05-01 11:07:43 [base.py:233] Readonly multi-modal warmup completed in 5.742s
(APIServer pid=1) INFO 05-01 11:07:43 [api_server.py:602] Starting vLLM server on http://0.0.0.0:8000
(APIServer pid=1) INFO 05-01 11:07:43 [launcher.py:37] Available routes are:
(APIServer pid=1) INFO 05-01 11:07:43 [launcher.py:46] Route: /openapi.json, Methods: HEAD, GET
(APIServer pid=1) INFO 05-01 11:07:43 [launcher.py:46] Route: /docs, Methods: HEAD, GET
(APIServer pid=1) INFO 05-01 11:07:43 [launcher.py:46] Route: /docs/oauth2-redirect, Methods: HEAD, GET
(APIServer pid=1) INFO 05-01 11:07:43 [launcher.py:46] Route: /redoc, Methods: HEAD, GET
(APIServer pid=1) INFO 05-01 11:07:43 [launcher.py:46] Route: /tokenize, Methods: POST
(APIServer pid=1) INFO 05-01 11:07:43 [launcher.py:46] Route: /detokenize, Methods: POST
(APIServer pid=1) INFO 05-01 11:07:43 [launcher.py:46] Route: /load, Methods: GET
(APIServer pid=1) INFO 05-01 11:07:43 [launcher.py:46] Route: /version, Methods: GET
(APIServer pid=1) INFO 05-01 11:07:43 [launcher.py:46] Route: /health, Methods: GET
(APIServer pid=1) INFO 05-01 11:07:43 [launcher.py:46] Route: /metrics, Methods: GET
(APIServer pid=1) INFO 05-01 11:07:43 [launcher.py:46] Route: /v1/models, Methods: GET
(APIServer pid=1) INFO 05-01 11:07:43 [launcher.py:46] Route: /ping, Methods: GET
(APIServer pid=1) INFO 05-01 11:07:43 [launcher.py:46] Route: /ping, Methods: POST
(APIServer pid=1) INFO 05-01 11:07:43 [launcher.py:46] Route: /invocations, Methods: POST
(APIServer pid=1) INFO 05-01 11:07:43 [launcher.py:46] Route: /v1/chat/completions, Methods: POST
(APIServer pid=1) INFO 05-01 11:07:43 [launcher.py:46] Route: /v1/chat/completions/batch, Methods: POST
(APIServer pid=1) INFO 05-01 11:07:43 [launcher.py:46] Route: /v1/responses, Methods: POST
(APIServer pid=1) INFO 05-01 11:07:43 [launcher.py:46] Route: /v1/responses/{response_id}, Methods: GET
(APIServer pid=1) INFO 05-01 11:07:43 [launcher.py:46] Route: /v1/responses/{response_id}/cancel, Methods: POST
(APIServer pid=1) INFO 05-01 11:07:43 [launcher.py:46] Route: /v1/completions, Methods: POST
(APIServer pid=1) INFO 05-01 11:07:43 [launcher.py:46] Route: /v1/messages, Methods: POST
(APIServer pid=1) INFO 05-01 11:07:43 [launcher.py:46] Route: /v1/messages/count_tokens, Methods: POST
(APIServer pid=1) INFO 05-01 11:07:43 [launcher.py:46] Route: /inference/v1/generate, Methods: POST
(APIServer pid=1) INFO 05-01 11:07:43 [launcher.py:46] Route: /scale_elastic_ep, Methods: POST
(APIServer pid=1) INFO 05-01 11:07:43 [launcher.py:46] Route: /is_scaling_elastic_ep, Methods: POST
(APIServer pid=1) INFO 05-01 11:07:43 [launcher.py:46] Route: /generative_scoring, Methods: POST
(APIServer pid=1) INFO 05-01 11:07:43 [launcher.py:46] Route: /v1/chat/completions/render, Methods: POST
(APIServer pid=1) INFO 05-01 11:07:43 [launcher.py:46] Route: /v1/completions/render, Methods: POST
(APIServer pid=1) INFO:     Started server process [1]
(APIServer pid=1) INFO:     Waiting for application startup.
(APIServer pid=1) INFO:     Application startup complete.
(APIServer pid=1) INFO:     172.19.0.1:51606 - "GET /v1/models HTTP/1.1" 200 OK
```

### verify-full.sh output

```text
launch.sh output instead:

[preflight] checking environment...
[preflight] docker:  29.3.0 (compose v2 ok)
[preflight] gpu:     2× detected
[preflight]            GPU 0: NVIDIA GeForce RTX 3090 (UUID: GPU-22ea9905-0f65-0be4-844c-0043d79cafd6)
[preflight]            GPU 1: NVIDIA GeForce RTX 3090 (UUID: GPU-4736b658-a06e-97a9-70ce-f25a7ea76779)
[preflight] WARN:  GPU(s) already have significant VRAM in use:
[preflight]            GPU 0: 1199 MiB in use
[preflight]        Boot may OOM. Free VRAM with 'nvidia-smi' / 'docker stop ...' first.
[preflight] ok.


club-3090 launcher — let's pick the right config for your workload.
(Use --variant <name> next time to skip the wizard.)


How many RTX 3090s?
  1) 1× 3090 (24 GB)
  2) 2× 3090 (PCIe / no NVLink)
Choice [1-2]: 2
[preflight] gpu:     2× detected
[preflight]            GPU 0: NVIDIA GeForce RTX 3090 (UUID: GPU-22ea9905-0f65-0be4-844c-0043d79cafd6)
[preflight]            GPU 1: NVIDIA GeForce RTX 3090 (UUID: GPU-4736b658-a06e-97a9-70ce-f25a7ea76779)

What's your dual-card priority?
  1) Balanced default — 262K + vision + 2 streams (recommended)
  2) Multi-tenant — 4 concurrent streams @ 262K, TQ3 KV
  3) Peak code TPS with vision (185K, DFlash N=5)
  4) Peak code TPS no vision (200K, DFlash N=5)
Choice [1-4]: 1

[wizard] picked vLLM — chosen for spec-decode (MTP), tool-call extraction, and best TPS.
[wizard]   Watch out for the prefill cliffs (Cliff 1 = 25K+ tool returns; Cliff 2 = 50-60K
[wizard]   single prompts on TQ3) — see docs/SINGLE_CARD.md for the safe-config map.

[launch] selected variant: vllm/dual

[switch] no club-3090 container running
[switch] bringing up: vllm/dual  (models/qwen3.6-27b/vllm/compose/docker-compose.dual.yml)
[+] Running 1/1
 ✔ Container vllm-qwen36-27b-dual  Started                                                                         0.9s
[switch] waiting for http://localhost:8010/v1/models (timeout 600s)...
[switch]   60s elapsed, still waiting...
[switch]   120s elapsed, still waiting...
[switch]   180s elapsed, still waiting...
[switch] ✓ ready
[switch] done. Try:  curl -s http://localhost:8010/v1/models | jq .

[launch] running verify-full.sh against the new server...

Running FULL functional test against http://localhost:8020 (model=qwen3.6-27b-autoround, container=vllm-qwen36-27b)

[1/8] Server reachable on /v1/models ...
  ✗ no response from http://localhost:8020/v1/models
    → Start the stack: cd compose && docker compose up -d ; docker logs -f vllm-qwen36-27b
[2/8] Genesis patches applied ...
  ⊘ container 'vllm-qwen36-27b' not found (skipped)
[3/8] Basic completion — capital of France ...
  ✗ completion request failed
    → Check docker logs vllm-qwen36-27b
[4/8] Tool calling ...
  ✗ tool-call request failed
    → Check docker logs
[5/8] Streaming (SSE) ...
  ✗ streaming request failed
    → Check docker logs
[6/8] Thinking / reasoning mode ...
  ✗ thinking request failed
    → Check docker logs
[7/8] Output quality / cascade detection (2K-token completion) ...
  ✗ output quality request failed
    → Check docker logs vllm-qwen36-27b
[8/8] MTP acceptance length threshold ...
  ⊘ container 'vllm-qwen36-27b' not found (skipped)

6 check(s) failed. See hints above.

[launch] some checks failed — see hints above. Common cases:
  - 'reasoning field empty' on llama.cpp = expected (parser gap, not a bug)
  - 'Genesis patches' / 'MTP acceptance' skipped on llama.cpp = expected (vLLM-only checks)
```

### nvidia-smi output

```text
Fri May  1 12:11:10 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 590.48.01              Driver Version: 595.79         CUDA Version: 13.2     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3090        On  |   00000000:01:00.0  On |                  N/A |
| 30%   36C    P8             36W /  270W |   23555MiB /  24576MiB |     13%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA GeForce RTX 3090        On  |   00000000:05:00.0 Off |                  N/A |
|  0%   39C    P8             14W /  270W |   21820MiB /  24576MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A              83      C   /python3.12                           N/A      |
|    1   N/A  N/A              83      C   /python3.12                           N/A      |
+-----------------------------------------------------------------------------------------+
```

### GPU configuration

2x RTX 3090 no NvLink.  In WSL

### Compose variant

docker-compose.dual.yml

### club-3090 commit

6bff99a

**Comment by noonghunna** [comment]
Thanks for the clean repro — bug confirmed and fixed in [`77ca576`](https://github.com/noonghunna/club-3090/commit/77ca576).

**Root cause:** `launch.sh` had the per-variant port mapping defined (used to print the endpoint URL at the very end) but it was only resolved AFTER the `verify-full.sh` call. The verify call ran with no URL/CONTAINER env vars, so it fell back to its built-in defaults (`URL=http://localhost:8020`, `CONTAINER=vllm-qwen36-27b`). That's why your dual stack booted cleanly on `:8010` with `vllm-qwen36-27b-dual` but verify hit `:8020` + `vllm-qwen36-27b` and reported 6/8 failed.

**Fix:**
- Moved the port-resolution block above the verify call.
- Added a per-variant `LAUNCH_DEFAULT_CONTAINER` mapping mirroring `LAUNCH_DEFAULT_PORT` (covers all 12 variants — vllm/{default, long-vision, long-text, bounded-thinking, tools-text, minimal, dual, dual-turbo, dual-dflash, dual-dflash-noviz} and llamacpp/{default, concurrent}).
- Pass `URL=$ENDPOINT_URL CONTAINER=$ENDPOINT_CONTAINER bash $VERIFY` so verify-full.sh sees the right values.
- Surfaced the resolved values in the launcher line so it's visible at run time: `[launch] running verify-full.sh against the new server (URL=http://localhost:8010, CONTAINER=vllm-qwen36-27b-dual)...`

To pull the fix:

```bash
cd <your club-3090 clone>
git pull
bash scripts/launch.sh   # re-run the wizard
```

Your stack is fine — the boot logs you posted show the model loaded and `Application startup complete.` on `:8000` (mapped to `:8010` host-side), and `nvidia-smi` shows real VRAM use on both cards. Just the launcher-side verify wiring was off.

Side notes from your logs that aren't bugs but worth knowing:

- `WARNING ... pin_memory=False as WSL is detected` — vLLM's standard WSL warning, modest TPS hit. Bare-metal Linux avoids it. Not a blocker.
- `CUDAGraphMode.FULL_AND_PIECEWISE is not supported with spec-decode for attention backend FlashInferBackend; setting cudagraph_mode=PIECEWISE` — expected, vLLM auto-falls-back. Doesn't affect correctness.
- `dual.yml` ships at 262K + TQ3 KV; you already have ~88 GB total VRAM headroom, so you're well within safe territory for Cliff 1 / Cliff 2 unless you're sending single 50K+ token prompts (those hit Cliff 2 — DeltaNet GDN — which TP=2 splits across cards but doesn't fully eliminate at extreme single-shot lengths). See [#16](https://github.com/noonghunna/club-3090/issues/16) for the catalog.

Closing this once you confirm the pull resolves it on your end.

**Comment by noonghunna** [comment]
Closed by [`77ca576`](https://github.com/noonghunna/club-3090/commit/77ca576) — `scripts/launch.sh` now resolves the per-variant `PORT` and `CONTAINER` defaults from `LAUNCH_DEFAULT_PORT[$VARIANT]` and `LAUNCH_DEFAULT_CONTAINER[$VARIANT]` and passes them as env vars to `verify-full.sh`. The mappings are kept in sync with `switch.sh` (e.g. `vllm/dual` → port 8010 + container `vllm-qwen36-27b-dual`).

Sorry for the delay closing this — fix landed before today's [v0.20 migration PR #23](https://github.com/noonghunna/club-3090/pull/23) but the issue was missed in the cleanup. Pulling latest master will get you the fix.

Repro path:
```bash
git pull
bash scripts/launch.sh
# pick 2× 3090 → option 1 (dual.yml)
# verify-full.sh now correctly uses URL=http://localhost:8010 + CONTAINER=vllm-qwen36-27b-dual
```

If you still see the wrong port/container after pulling, please reopen.
