### ISSUE TITLE
[bug] CUDA driver error: device not ready when running a big promot (around 157,000 tokens)

### ISSUE THREAD

**Issue by RossNE99** [noonghunna/club-3090#50]
### What happened?

I ran docker-compose.dual.yml

i ran a couple of smaller prompts, then i tied to run a 156k token promt from Kilo code and i got the error before, i tried this a few times and i get this crash every time even without running smaller promts first 

### Steps to reproduce

```bash
run docker-compose.dual.yml
Run a long promot 157k via klio code
```

### Rig report — paste contents of `bash scripts/report.sh [--verify | --soak | --bench | --full]`

```markdown
rossy@Ross-PC:~/club-3090$ cat my-rig.md
# club-3090 rig report

Generated: 2026-05-04 17:24:16 UTC

_Redacted output (paths, host, user, tokens). Re-run with `--no-redact` for full data._

## System

- **OS:** Ubuntu 24.04.4 LTS
- **Kernel:** 6.6.87.2-microsoft-standard-WSL2
- **Environment:** WSL2 (kernel reports WSL2)
- **Locale:** C.UTF-8
- **Timezone:** BST
- **Uptime:** up 1 hour, 9 minutes

## CPU + RAM

- **CPU:** 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz (16 threads)
- **RAM:** 15Gi total, 13Gi available
- **Swap:** 4.0Gi

## Disk

- **~/club-3090/models-cache:** 927G available, ext4 filesystem

## GPU hardware

- **GPU 0:** NVIDIA GeForce RTX 3090 | 24576 MiB | driver 596.36 | VBIOS 94.02.26.48.15 | persistence=Enabled
  - **Power:** limit=420.00 W (default=420.00 W, max=450.00 W) | current_draw=13.28 W
- **GPU 1:** NVIDIA GeForce RTX 3090 | 24576 MiB | driver 596.36 | VBIOS 94.02.26.48.78 | persistence=Enabled
  - **Power:** limit=350.00 W (default=350.00 W, max=366.00 W) | current_draw=14.19 W
- **CUDA Runtime (per driver):** 13.2
- **ECC mode:** [N/A] (3090s don't have ECC; expect N/A)

### NVLink

_No NVLink detected (PCIe-only)_

### Topology

<details><summary>PCIe / GPU topology matrix</summary>


        GPU0    GPU1    CPU Affinity    NUMA Affinity   GPU NUMA ID
Failed to run topology matrix



</details>

### Full nvidia-smi

<details><summary>Full nvidia-smi output</summary>


Mon May  4 18:24:21 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 595.71.01              Driver Version: 596.36         CUDA Version: 13.2     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3090        On  |   00000000:01:00.0 Off |                  N/A |
|  0%   36C    P8             13W /  420W |       0MiB /  24576MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA GeForce RTX 3090        On  |   00000000:02:00.0 Off |                  N/A |
|  0%   27C    P8             14W /  350W |       0MiB /  24576MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+


</details>

## Display / desktop state

- **$DISPLAY:** :0 (X11 / Wayland session present)
- **$WAYLAND_DISPLAY:** wayland-0
- **Display processes running:** none detected
- **GPU 0 idle VRAM:** 0 MiB ✓
- **GPU 1 idle VRAM:** 0 MiB ✓

## Container runtime

- **Docker:** 29.4.1
- **docker compose (v2):** 5.1.3

## Stack version

- **club-3090:** `f55b0a7` (branch: `master`)
- **Working tree:** ⚠ has uncommitted changes (run `git status` to inspect)
- **GENESIS_PIN default:** `2db18df` (per scripts/setup.sh)
- **Cached vLLM images:**
  - tag `nightly-7a1eb8ac2ec4ea69338c51dc7afd4b15010abfa8` digest `sha256:7923b48047be655ab8a18f2d152f7a67a03acb80866ee7cae298fea13c7ac9c7` (6 days ago)

## Active container

- **Name:** `vllm-qwen36-27b-dual`
- **Status:** Up 22 seconds
- **Ports:** 0.0.0.0:8010->8000/tcp, [::]:8010->8000/tcp
- **Image:** `vllm/vllm-openai:nightly-7a1eb8ac2ec4ea69338c51dc7afd4b15010abfa8`

### Container Python / CUDA versions

- **PyTorch:** `torch=2.11.0+cu130 torch_cuda_build=13.0 cudnn=91900`
- **vLLM:** `0.20.1rc1.dev16+g7a1eb8ac2`
- **nvidia-smi inside container:**
  
  0, NVIDIA GeForce RTX 3090, 596.36
  1, NVIDIA GeForce RTX 3090, 596.36
  

### Boot log highlights

**KV pool sizing:**

(Worker_TP0 pid=60) INFO 05-04 17:07:49 [gpu_worker.py:440] Available KV cache memory: 11.49 GiB
(EngineCore pid=51) INFO 05-04 17:07:49 [kv_cache_utils.py:1713] GPU KV cache size: 176,000 tokens
(EngineCore pid=51) INFO 05-04 17:07:49 [kv_cache_utils.py:1718] Maximum concurrency for 262,144 tokens per request: 2.47x


**Engine config (CLI flags + engine init):**

(APIServer pid=1) INFO 05-04 17:04:14 [utils.py:233] non-default args: {'model_tag': '~/.cache/huggingface/qwen3.6-27b-autoround-int4', 'default_chat_template_kwargs': {'enable_thinking': False}, 'enable_auto_tool_choice': True, 'tool_call_parser': 'qwen3_coder', 'host': '0.0.0.0', 'model': '~/.cache/huggingface/qwen3.6-27b-autoround-int4', 'trust_remote_code': True, 'dtype': 'float16', 'max_model_len': 262144, 'quantization': 'auto_round', 'served_model_name': ['qwen3.6-27b-autoround'], 'reasoning_parser': 'qwen3', 'tensor_parallel_size': 2, 'disable_custom_all_reduce': True, 'kv_cache_dtype': 'fp8_e5m2', 'enable_prefix_caching': True, 'max_num_batched_tokens': 8192, 'max_num_seqs': 2, 'enable_chunked_prefill': True, 'speculative_config': {'method': 'mtp', 'num_speculative_tokens': 3}}
(EngineCore pid=51) INFO 05-04 17:04:43 [core.py:109] Initializing a V1 LLM engine (v0.20.1rc1.dev16+g7a1eb8ac2) with config: model='~/.cache/huggingface/qwen3.6-27b-autoround-int4', speculative_config=SpeculativeConfig(method='mtp', model='~/.cache/huggingface/qwen3.6-27b-autoround-int4', num_spec_tokens=3), tokenizer='~/.cache/huggingface/qwen3.6-27b-autoround-int4', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=262144, download_dir=None, load_format=auto, tensor_parallel_size=2, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=inc, quantization_config=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=fp8_e5m2, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='qwen3', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=qwen3.6-27b-autoround, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'ir_enable_torch_wrap': True, 'splitting_ops': ['vllm::unified_attention_with_output', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::gdn_attention_core_xpu', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::deepseek_v4_attention', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 16, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto')


**Recent warnings/errors (last 5):**

WARNING 05-04 17:04:14 [argparse_utils.py:257] With `vllm serve`, you should provide the model as a positional argument or in a config file instead of via the `--model` option. The `--model` option will be removed in a future version.
WARNING 05-04 17:04:46 [interface.py:686] Using 'pin_memory=False' as WSL is detected. This may slow down the performance.
WARNING 05-04 17:04:46 [interface.py:686] Using 'pin_memory=False' as WSL is detected. This may slow down the performance.
WARNING 05-04 17:24:14 [interface.py:686] Using 'pin_memory=False' as WSL is detected. This may slow down the performance.
WARNING 05-04 17:24:15 [argparse_utils.py:257] With `vllm serve`, you should provide the model as a positional argument or in a config file instead of via the `--model` option. The `--model` option will be removed in a future version.


### Full boot log (first 200 lines)

<details><summary>First 200 lines of docker logs</summary>


WARNING 05-04 17:04:14 [interface.py:686] Using 'pin_memory=False' as WSL is detected. This may slow down the performance.
WARNING 05-04 17:04:14 [argparse_utils.py:257] With `vllm serve`, you should provide the model as a positional argument or in a config file instead of via the `--model` option. The `--model` option will be removed in a future version.
(APIServer pid=1) INFO 05-04 17:04:14 [utils.py:299]
(APIServer pid=1) INFO 05-04 17:04:14 [utils.py:299]        █     █     █▄   ▄█
(APIServer pid=1) INFO 05-04 17:04:14 [utils.py:299]  ▄▄ ▄█ █     █     █ ▀▄▀ █  version 0.20.1rc1.dev16+g7a1eb8ac2
(APIServer pid=1) INFO 05-04 17:04:14 [utils.py:299]   █▄█▀ █     █     █     █  model   ~/.cache/huggingface/qwen3.6-27b-autoround-int4
(APIServer pid=1) INFO 05-04 17:04:14 [utils.py:299]    ▀▀  ▀▀▀▀▀ ▀▀▀▀▀ ▀     ▀
(APIServer pid=1) INFO 05-04 17:04:14 [utils.py:299]
(APIServer pid=1) INFO 05-04 17:04:14 [utils.py:233] non-default args: {'model_tag': '~/.cache/huggingface/qwen3.6-27b-autoround-int4', 'default_chat_template_kwargs': {'enable_thinking': False}, 'enable_auto_tool_choice': True, 'tool_call_parser': 'qwen3_coder', 'host': '0.0.0.0', 'model': '~/.cache/huggingface/qwen3.6-27b-autoround-int4', 'trust_remote_code': True, 'dtype': 'float16', 'max_model_len': 262144, 'quantization': 'auto_round', 'served_model_name': ['qwen3.6-27b-autoround'], 'reasoning_parser': 'qwen3', 'tensor_parallel_size': 2, 'disable_custom_all_reduce': True, 'kv_cache_dtype': 'fp8_e5m2', 'enable_prefix_caching': True, 'max_num_batched_tokens': 8192, 'max_num_seqs': 2, 'enable_chunked_prefill': True, 'speculative_config': {'method': 'mtp', 'num_speculative_tokens': 3}}
(APIServer pid=1) INFO 05-04 17:04:22 [nixl_utils.py:20] Setting UCX_RCACHE_MAX_UNRELEASED to '1024' to avoid a rare memory leak in UCX when using NIXL.
(APIServer pid=1) INFO 05-04 17:04:22 [nixl_utils.py:32] NIXL is available
(APIServer pid=1) INFO 05-04 17:04:22 [model.py:563] Resolved architecture: Qwen3_5ForConditionalGeneration
(APIServer pid=1) WARNING 05-04 17:04:22 [model.py:2030] Casting torch.bfloat16 to torch.float16.
(APIServer pid=1) INFO 05-04 17:04:22 [model.py:1692] Using max model len 262144
(APIServer pid=1) INFO 05-04 17:04:23 [cache.py:261] Using fp8_e5m2 data type to store kv cache. It reduces the GPU memory footprint and boosts the performance. Meanwhile, it may cause accuracy drop without a proper scaling factor
(APIServer pid=1) INFO 05-04 17:04:28 [model.py:563] Resolved architecture: Qwen3_5MTP
(APIServer pid=1) WARNING 05-04 17:04:28 [model.py:2030] Casting torch.bfloat16 to torch.float16.
(APIServer pid=1) INFO 05-04 17:04:28 [model.py:1692] Using max model len 262144
(APIServer pid=1) WARNING 05-04 17:04:28 [speculative.py:659] Enabling num_speculative_tokens > 1 will run multiple times of forward on same MTP layer,which may result in lower acceptance rate
(APIServer pid=1) INFO 05-04 17:04:28 [scheduler.py:239] Chunked prefill is enabled with max_num_batched_tokens=8192.
(APIServer pid=1) WARNING 05-04 17:04:28 [config.py:367] Mamba cache mode is set to 'align' for Qwen3_5ForConditionalGeneration by default when prefix caching is enabled
(APIServer pid=1) INFO 05-04 17:04:28 [config.py:387] Warning: Prefix caching in Mamba cache 'align' mode is currently enabled. Its support for Mamba layers is experimental. Please report any issues you may observe.
(APIServer pid=1) INFO 05-04 17:04:28 [vllm.py:840] Asynchronous scheduling is enabled.
(APIServer pid=1) INFO 05-04 17:04:28 [kernel.py:205] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'])
(APIServer pid=1) [transformers] `Qwen2VLImageProcessorFast` is deprecated. The `Fast` suffix for image processors has been removed; use `Qwen2VLImageProcessor` instead.
(APIServer pid=1) [transformers] The `use_fast` parameter is deprecated and will be removed in a future version. Use `backend="torchvision"` instead of `use_fast=True`, or `backend="pil"` instead of `use_fast=False`.
(EngineCore pid=51) INFO 05-04 17:04:43 [core.py:109] Initializing a V1 LLM engine (v0.20.1rc1.dev16+g7a1eb8ac2) with config: model='~/.cache/huggingface/qwen3.6-27b-autoround-int4', speculative_config=SpeculativeConfig(method='mtp', model='~/.cache/huggingface/qwen3.6-27b-autoround-int4', num_spec_tokens=3), tokenizer='~/.cache/huggingface/qwen3.6-27b-autoround-int4', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=262144, download_dir=None, load_format=auto, tensor_parallel_size=2, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=inc, quantization_config=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=fp8_e5m2, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='qwen3', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=qwen3.6-27b-autoround, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'ir_enable_torch_wrap': True, 'splitting_ops': ['vllm::unified_attention_with_output', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::gdn_attention_core_xpu', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::deepseek_v4_attention', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 16, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto')
(EngineCore pid=51) INFO 05-04 17:04:43 [multiproc_executor.py:139] DP group leader: node_rank=0, node_rank_within_dp=0, master_addr=127.0.0.1, mq_connect_ip=172.20.0.2 (local), world_size=2, local_world_size=2
INFO 05-04 17:04:48 [nixl_utils.py:32] NIXL is available
INFO 05-04 17:04:48 [nixl_utils.py:32] NIXL is available
WARNING 05-04 17:04:46 [interface.py:686] Using 'pin_memory=False' as WSL is detected. This may slow down the performance.
WARNING 05-04 17:04:46 [interface.py:686] Using 'pin_memory=False' as WSL is detected. This may slow down the performance.
[transformers] `Qwen2VLImageProcessorFast` is deprecated. The `Fast` suffix for image processors has been removed; use `Qwen2VLImageProcessor` instead.
[transformers] `Qwen2VLImageProcessorFast` is deprecated. The `Fast` suffix for image processors has been removed; use `Qwen2VLImageProcessor` instead.
(Worker pid=60) INFO 05-04 17:04:48 [parallel_state.py:1402] world_size=2 rank=0 local_rank=0 distributed_init_method=tcp://127.0.0.1:40849 backend=nccl
(Worker pid=61) INFO 05-04 17:04:48 [parallel_state.py:1402] world_size=2 rank=1 local_rank=1 distributed_init_method=tcp://127.0.0.1:40849 backend=nccl
(Worker pid=60) INFO 05-04 17:04:49 [pynccl.py:111] vLLM is using nccl==2.28.9
(Worker pid=60) WARNING 05-04 17:04:50 [symm_mem.py:66] SymmMemCommunicator: Device capability 8.6 not supported, communicator is not available.
(Worker pid=61) WARNING 05-04 17:04:50 [symm_mem.py:66] SymmMemCommunicator: Device capability 8.6 not supported, communicator is not available.
(Worker pid=60) INFO 05-04 17:04:50 [parallel_state.py:1715] rank 0 in world size 2 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(Worker pid=60) INFO 05-04 17:04:50 [topk_topp_sampler.py:51] Using FlashInfer for top-p & top-k sampling.
(Worker pid=61) WARNING 05-04 17:04:50 [__init__.py:206] min_p and logit_bias parameters won't work with speculative decoding.
(Worker pid=60) WARNING 05-04 17:04:50 [__init__.py:206] min_p and logit_bias parameters won't work with speculative decoding.
(Worker pid=61) [transformers] The `use_fast` parameter is deprecated and will be removed in a future version. Use `backend="torchvision"` instead of `use_fast=True`, or `backend="pil"` instead of `use_fast=False`.
(Worker pid=60) [transformers] The `use_fast` parameter is deprecated and will be removed in a future version. Use `backend="torchvision"` instead of `use_fast=True`, or `backend="pil"` instead of `use_fast=False`.
(Worker_TP0 pid=60) INFO 05-04 17:04:57 [gpu_model_runner.py:4777] Starting to load model ~/.cache/huggingface/qwen3.6-27b-autoround-int4...
(Worker_TP0 pid=60) INFO 05-04 17:04:57 [cuda.py:423] Using backend AttentionBackendEnum.FLASH_ATTN for vit attention
(Worker_TP0 pid=60) INFO 05-04 17:04:57 [mm_encoder_attention.py:372] Using AttentionBackendEnum.FLASH_ATTN for MMEncoderAttention.
(Worker_TP1 pid=61) INFO 05-04 17:04:57 [gptq_marlin.py:387] Using MarlinLinearKernel for GPTQMarlinLinearMethod
(Worker_TP0 pid=60) INFO 05-04 17:04:57 [gptq_marlin.py:387] Using MarlinLinearKernel for GPTQMarlinLinearMethod
(Worker_TP0 pid=60) INFO 05-04 17:04:57 [gdn_linear_attn.py:153] Using Triton/FLA GDN prefill kernel
(Worker_TP0 pid=60) INFO 05-04 17:04:57 [cuda.py:368] Using FLASHINFER attention backend out of potential backends: ['FLASHINFER', 'TRITON_ATTN'].
(Worker_TP0 pid=60) INFO 05-04 17:04:58 [weight_utils.py:904] Filesystem type for checkpoints: EXT4. Checkpoint size: 17.69 GiB. Available RAM: 9.10 GiB.
(Worker_TP0 pid=60) INFO 05-04 17:04:58 [weight_utils.py:934] Auto-prefetch is disabled because the filesystem (EXT4) is not a recognized network FS (NFS/Lustre) and the checkpoint size (17.69 GiB) exceeds 90% of available RAM (9.10 GiB).
Loading safetensors checkpoint shards:   0% Completed | 0/11 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:   9% Completed | 1/11 [00:10<01:48, 10.88s/it]
Loading safetensors checkpoint shards:  18% Completed | 2/11 [00:18<01:18,  8.73s/it]
Loading safetensors checkpoint shards:  27% Completed | 3/11 [00:28<01:15,  9.41s/it]
Loading safetensors checkpoint shards:  36% Completed | 4/11 [00:36<01:01,  8.81s/it]
Loading safetensors checkpoint shards:  45% Completed | 5/11 [00:45<00:52,  8.80s/it]
Loading safetensors checkpoint shards:  55% Completed | 6/11 [00:53<00:43,  8.76s/it]
Loading safetensors checkpoint shards:  64% Completed | 7/11 [00:58<00:30,  7.57s/it]
Loading safetensors checkpoint shards:  73% Completed | 8/11 [01:08<00:25,  8.40s/it]
Loading safetensors checkpoint shards:  91% Completed | 10/11 [01:16<00:06,  6.13s/it]
Loading safetensors checkpoint shards: 100% Completed | 11/11 [01:16<00:00,  6.93s/it]
(Worker_TP0 pid=60)
(Worker_TP0 pid=60) INFO 05-04 17:06:14 [default_loader.py:384] Loading weights took 82.43 seconds
(Worker_TP0 pid=60) INFO 05-04 17:06:14 [gpu_model_runner.py:4801] Loading drafter model...
(Worker_TP0 pid=60) INFO 05-04 17:06:14 [vllm.py:840] Asynchronous scheduling is enabled.
(Worker_TP0 pid=60) INFO 05-04 17:06:14 [kernel.py:205] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'])
(Worker_TP0 pid=60) INFO 05-04 17:06:14 [weight_utils.py:904] Filesystem type for checkpoints: EXT4. Checkpoint size: 17.69 GiB. Available RAM: 8.53 GiB.
(Worker_TP0 pid=60) INFO 05-04 17:06:14 [weight_utils.py:934] Auto-prefetch is disabled because the filesystem (EXT4) is not a recognized network FS (NFS/Lustre) and the checkpoint size (17.69 GiB) exceeds 90% of available RAM (8.53 GiB).
Loading safetensors checkpoint shards:   0% Completed | 0/11 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:   9% Completed | 1/11 [00:00<00:03,  3.00it/s]
Loading safetensors checkpoint shards:  18% Completed | 2/11 [00:00<00:03,  2.72it/s]
Loading safetensors checkpoint shards:  27% Completed | 3/11 [00:00<00:02,  3.45it/s]
Loading safetensors checkpoint shards:  36% Completed | 4/11 [00:01<00:01,  3.54it/s]
(Worker_TP1 pid=61) INFO 05-04 17:06:16 [kernel.py:205] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'])
Loading safetensors checkpoint shards:  73% Completed | 8/11 [00:04<00:01,  1.52it/s]
Loading safetensors checkpoint shards:  91% Completed | 10/11 [00:05<00:00,  1.57it/s]
Loading safetensors checkpoint shards: 100% Completed | 11/11 [00:06<00:00,  1.38it/s]
Loading safetensors checkpoint shards: 100% Completed | 11/11 [00:06<00:00,  1.62it/s]
(Worker_TP0 pid=60)
(Worker_TP0 pid=60) INFO 05-04 17:06:21 [default_loader.py:384] Loading weights took 6.79 seconds
(Worker_TP1 pid=61) INFO 05-04 17:06:26 [llm_base_proposer.py:1460] Detected MTP model. Sharing target model embedding weights with the draft model.
(Worker_TP0 pid=60) INFO 05-04 17:06:26 [llm_base_proposer.py:1460] Detected MTP model. Sharing target model embedding weights with the draft model.
(Worker_TP0 pid=60) INFO 05-04 17:06:26 [llm_base_proposer.py:1516] Detected MTP model. Sharing target model lm_head weights with the draft model.
(Worker_TP1 pid=61) INFO 05-04 17:06:26 [llm_base_proposer.py:1516] Detected MTP model. Sharing target model lm_head weights with the draft model.
(Worker_TP0 pid=60) INFO 05-04 17:06:26 [gpu_model_runner.py:4879] Model loading took 8.93 GiB memory and 95.010459 seconds
(Worker_TP0 pid=60) INFO 05-04 17:06:26 [interface.py:606] Setting attention block size to 1600 tokens to ensure that attention page size is >= mamba page size.
(Worker_TP0 pid=60) INFO 05-04 17:06:26 [interface.py:630] Padding mamba page size by 0.25% to ensure that mamba page size and attention page size are exactly equal.
(Worker_TP1 pid=61) INFO 05-04 17:06:26 [interface.py:606] Setting attention block size to 1600 tokens to ensure that attention page size is >= mamba page size.
(Worker_TP1 pid=61) INFO 05-04 17:06:26 [interface.py:630] Padding mamba page size by 0.25% to ensure that mamba page size and attention page size are exactly equal.
(Worker_TP0 pid=60) INFO 05-04 17:06:26 [gpu_model_runner.py:5820] Encoder cache will be initialized with a budget of 16384 tokens, and profiled with 1 image items of the maximum feature size.
(Worker_TP0 pid=60) INFO 05-04 17:06:33 [backends.py:1069] Using cache directory: ~/.cache/vllm/torch_compile_cache/eda5c4a6b0/rank_0_0/backbone for vLLM's torch.compile
(Worker_TP0 pid=60) INFO 05-04 17:06:33 [backends.py:1128] Dynamo bytecode transform time: 3.21 s
(Worker_TP0 pid=60) INFO 05-04 17:06:42 [backends.py:290] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 10.347 s
(Worker_TP1 pid=61) INFO 05-04 17:06:42 [decorators.py:305] Directly load AOT compilation from path ~/.cache/vllm/torch_compile_cache/torch_aot_compile/d1182e8037d5fcd492b4c22970d9e1d67bd571e80d13bdf0e3a44d8f8d24f2c0/rank_1_0/model
(Worker_TP0 pid=60) INFO 05-04 17:06:42 [decorators.py:305] Directly load AOT compilation from path ~/.cache/vllm/torch_compile_cache/torch_aot_compile/d1182e8037d5fcd492b4c22970d9e1d67bd571e80d13bdf0e3a44d8f8d24f2c0/rank_0_0/model
(Worker_TP0 pid=60) INFO 05-04 17:06:42 [monitor.py:53] torch.compile took 14.24 s in total
(EngineCore pid=51) INFO 05-04 17:07:23 [shm_broadcast.py:681] No available shared memory broadcast block found in 60 seconds. This typically happens when some processes are hanging or doing some time-consuming work (e.g. compilation, weight/kv cache quantization).
(Worker_TP0 pid=60) INFO 05-04 17:07:43 [monitor.py:81] Initial profiling/warmup run took 65.69 s
(Worker_TP0 pid=60) INFO 05-04 17:07:44 [backends.py:1069] Using cache directory: ~/.cache/vllm/torch_compile_cache/eda5c4a6b0/rank_0_0/eagle_head for vLLM's torch.compile
(Worker_TP0 pid=60) INFO 05-04 17:07:44 [backends.py:1128] Dynamo bytecode transform time: 0.14 s
(Worker_TP0 pid=60) INFO 05-04 17:07:44 [backends.py:290] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 0.227 s
(Worker_TP0 pid=60) INFO 05-04 17:07:44 [decorators.py:305] Directly load AOT compilation from path ~/.cache/vllm/torch_compile_cache/torch_aot_compile/ad0602552ba7964a0f1a2a480e51983d22943774795f09d4cf039f93d7f5f709/rank_0_0/model
(Worker_TP0 pid=60) INFO 05-04 17:07:44 [monitor.py:53] torch.compile took 0.38 s in total
(Worker_TP1 pid=61) INFO 05-04 17:07:44 [decorators.py:305] Directly load AOT compilation from path ~/.cache/vllm/torch_compile_cache/torch_aot_compile/ad0602552ba7964a0f1a2a480e51983d22943774795f09d4cf039f93d7f5f709/rank_1_0/model
(Worker_TP0 pid=60) INFO 05-04 17:07:44 [monitor.py:81] Initial profiling/warmup run took 0.27 s
(Worker_TP1 pid=61) WARNING 05-04 17:07:47 [kv_cache_utils.py:1140] Add 3 padding layers, may waste at most 6.25% KV cache memory
(Worker_TP0 pid=60) WARNING 05-04 17:07:47 [kv_cache_utils.py:1140] Add 3 padding layers, may waste at most 6.25% KV cache memory
(Worker_TP1 pid=61) WARNING 05-04 17:07:47 [compilation.py:1390] CUDAGraphMode.FULL_AND_PIECEWISE is not supported with spec-decode for attention backend FlashInferBackend (support: AttentionCGSupport.UNIFORM_SINGLE_TOKEN_DECODE); setting cudagraph_mode=PIECEWISE
(Worker_TP0 pid=60) WARNING 05-04 17:07:47 [compilation.py:1390] CUDAGraphMode.FULL_AND_PIECEWISE is not supported with spec-decode for attention backend FlashInferBackend (support: AttentionCGSupport.UNIFORM_SINGLE_TOKEN_DECODE); setting cudagraph_mode=PIECEWISE
(Worker_TP0 pid=60) INFO 05-04 17:07:47 [gpu_model_runner.py:5963] Profiling CUDA graph memory: PIECEWISE=5 (largest=16)
(Worker_TP1 pid=61) INFO 05-04 17:07:47 [gpu_model_runner.py:5963] Profiling CUDA graph memory: PIECEWISE=5 (largest=16)
(Worker_TP1 pid=61) INFO 05-04 17:07:49 [gpu_model_runner.py:6042] Estimated CUDA graph memory: 0.13 GiB total
(Worker_TP0 pid=60) INFO 05-04 17:07:49 [gpu_model_runner.py:6042] Estimated CUDA graph memory: 0.13 GiB total
(Worker_TP1 pid=61) INFO 05-04 17:07:49 [gpu_worker.py:455] CUDA graph memory profiling is enabled (default since v0.21.0). The current --gpu-memory-utilization=0.9200 is equivalent to --gpu-memory-utilization=0.9144 without CUDA graph memory profiling. To maintain the same effective KV cache size as before, increase --gpu-memory-utilization to 0.9256. To disable, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=0.
(Worker_TP0 pid=60) INFO 05-04 17:07:49 [gpu_worker.py:440] Available KV cache memory: 11.49 GiB
(Worker_TP0 pid=60) INFO 05-04 17:07:49 [gpu_worker.py:455] CUDA graph memory profiling is enabled (default since v0.21.0). The current --gpu-memory-utilization=0.9200 is equivalent to --gpu-memory-utilization=0.9145 without CUDA graph memory profiling. To maintain the same effective KV cache size as before, increase --gpu-memory-utilization to 0.9255. To disable, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=0.
(EngineCore pid=51) WARNING 05-04 17:07:49 [kv_cache_utils.py:1140] Add 3 padding layers, may waste at most 6.25% KV cache memory
(EngineCore pid=51) INFO 05-04 17:07:49 [kv_cache_utils.py:1713] GPU KV cache size: 176,000 tokens
(EngineCore pid=51) INFO 05-04 17:07:49 [kv_cache_utils.py:1718] Maximum concurrency for 262,144 tokens per request: 2.47x
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 5/5 [00:00<00:00,  8.49it/s]
(Worker_TP1 pid=61) INFO 05-04 17:07:51 [gpu_worker.py:599] CUDA graph pool memory: 0.1 GiB (actual), 0.13 GiB (estimated), difference: 0.03 GiB (32.7%).
(Worker_TP0 pid=60) INFO 05-04 17:07:51 [gpu_model_runner.py:6133] Graph capturing finished in 1 secs, took 0.10 GiB
(Worker_TP0 pid=60) INFO 05-04 17:07:51 [gpu_worker.py:599] CUDA graph pool memory: 0.1 GiB (actual), 0.13 GiB (estimated), difference: 0.03 GiB (28.3%).
(EngineCore pid=51) INFO 05-04 17:07:51 [core.py:299] init engine (profile, create kv cache, warmup model) took 84.57 s (compilation: 14.64 s)
(EngineCore pid=51) INFO 05-04 17:07:53 [nixl_utils.py:32] NIXL is available
(EngineCore pid=51) [transformers] `Qwen2VLImageProcessorFast` is deprecated. The `Fast` suffix for image processors has been removed; use `Qwen2VLImageProcessor` instead.
(EngineCore pid=51) [transformers] The `use_fast` parameter is deprecated and will be removed in a future version. Use `backend="torchvision"` instead of `use_fast=True`, or `backend="pil"` instead of `use_fast=False`.
(EngineCore pid=51) WARNING 05-04 17:07:59 [interface.py:686] Using 'pin_memory=False' as WSL is detected. This may slow down the performance.
(EngineCore pid=51) INFO 05-04 17:07:59 [vllm.py:840] Asynchronous scheduling is enabled.
(EngineCore pid=51) INFO 05-04 17:07:59 [kernel.py:205] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'])
(APIServer pid=1) INFO 05-04 17:08:04 [api_server.py:598] Supported tasks: ['generate']
(APIServer pid=1) INFO 05-04 17:08:08 [parser_manager.py:202] "auto" tool choice has been enabled.
(APIServer pid=1) WARNING 05-04 17:08:08 [model.py:1449] Default vLLM sampling parameters have been overridden by the model's `generation_config.json`: `{'temperature': 1.0, 'top_k': 20, 'top_p': 0.95}`. If this is not intended, please relaunch vLLM instance with `--generation-config vllm`.
(APIServer pid=1) INFO 05-04 17:08:15 [hf.py:314] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.
(APIServer pid=1) INFO 05-04 17:08:24 [base.py:233] Multi-modal warmup completed in 9.057s
(APIServer pid=1) INFO 05-04 17:08:30 [base.py:233] Readonly multi-modal warmup completed in 8.032s
(APIServer pid=1) INFO 05-04 17:08:30 [api_server.py:602] Starting vLLM server on http://0.0.0.0:8000
(APIServer pid=1) INFO 05-04 17:08:30 [launcher.py:37] Available routes are:
(APIServer pid=1) INFO 05-04 17:08:30 [launcher.py:46] Route: /openapi.json, Methods: HEAD, GET
(APIServer pid=1) INFO 05-04 17:08:30 [launcher.py:46] Route: /docs, Methods: HEAD, GET
(APIServer pid=1) INFO 05-04 17:08:30 [launcher.py:46] Route: /docs/oauth2-redirect, Methods: HEAD, GET
(APIServer pid=1) INFO 05-04 17:08:30 [launcher.py:46] Route: /redoc, Methods: HEAD, GET
(APIServer pid=1) INFO 05-04 17:08:30 [launcher.py:46] Route: /tokenize, Methods: POST
(APIServer pid=1) INFO 05-04 17:08:30 [launcher.py:46] Route: /detokenize, Methods: POST
(APIServer pid=1) INFO 05-04 17:08:30 [launcher.py:46] Route: /load, Methods: GET
(APIServer pid=1) INFO 05-04 17:08:30 [launcher.py:46] Route: /version, Methods: GET
(APIServer pid=1) INFO 05-04 17:08:30 [launcher.py:46] Route: /health, Methods: GET
(APIServer pid=1) INFO 05-04 17:08:30 [launcher.py:46] Route: /metrics, Methods: GET
(APIServer pid=1) INFO 05-04 17:08:30 [launcher.py:46] Route: /v1/models, Methods: GET
(APIServer pid=1) INFO 05-04 17:08:30 [launcher.py:46] Route: /ping, Methods: GET
(APIServer pid=1) INFO 05-04 17:08:30 [launcher.py:46] Route: /ping, Methods: POST
(APIServer pid=1) INFO 05-04 17:08:30 [launcher.py:46] Route: /invocations, Methods: POST
(APIServer pid=1) INFO 05-04 17:08:30 [launcher.py:46] Route: /v1/chat/completions, Methods: POST
(APIServer pid=1) INFO 05-04 17:08:30 [launcher.py:46] Route: /v1/chat/completions/batch, Methods: POST
(APIServer pid=1) INFO 05-04 17:08:30 [launcher.py:46] Route: /v1/responses, Methods: POST
(APIServer pid=1) INFO 05-04 17:08:30 [launcher.py:46] Route: /v1/responses/{response_id}, Methods: GET
(APIServer pid=1) INFO 05-04 17:08:30 [launcher.py:46] Route: /v1/responses/{response_id}/cancel, Methods: POST
(APIServer pid=1) INFO 05-04 17:08:30 [launcher.py:46] Route: /v1/completions, Methods: POST
(APIServer pid=1) INFO 05-04 17:08:30 [launcher.py:46] Route: /v1/messages, Methods: POST
(APIServer pid=1) INFO 05-04 17:08:30 [launcher.py:46] Route: /v1/messages/count_tokens, Methods: POST
(APIServer pid=1) INFO 05-04 17:08:30 [launcher.py:46] Route: /inference/v1/generate, Methods: POST
(APIServer pid=1) INFO 05-04 17:08:30 [launcher.py:46] Route: /scale_elastic_ep, Methods: POST
(APIServer pid=1) INFO 05-04 17:08:30 [launcher.py:46] Route: /is_scaling_elastic_ep, Methods: POST
(APIServer pid=1) INFO 05-04 17:08:30 [launcher.py:46] Route: /generative_scoring, Methods: POST
(APIServer pid=1) INFO 05-04 17:08:30 [launcher.py:46] Route: /v1/chat/completions/render, Methods: POST
(APIServer pid=1) INFO 05-04 17:08:30 [launcher.py:46] Route: /v1/completions/render, Methods: POST
(APIServer pid=1) INFO:     Started server process [1]
(APIServer pid=1) INFO:     Waiting for application startup.
(APIServer pid=1) INFO:     Application startup complete.
(APIServer pid=1) INFO:     172.20.0.1:48844 - "GET /v1/models HTTP/1.1" 200 OK
(APIServer pid=1) INFO 05-04 17:09:59 [loggers.py:271] Engine 000: Avg prompt throughput: 411.6 tokens/s, Avg generation throughput: 0.1 tokens/s, Running: 1 reqs, Waiting: 0 reqs, GPU KV cache usage: 3.4%, Prefix cache hit rate: 0.0%
(APIServer pid=1) INFO:     172.20.0.1:34066 - "POST /v1/chat/completions HTTP/1.1" 200 OK
(APIServer pid=1) INFO:     172.20.0.1:34066 - "POST /v1/chat/completions HTTP/1.1" 200 OK
(APIServer pid=1) INFO 05-04 17:10:09 [loggers.py:271] Engine 000: Avg prompt throughput: 2.9 tokens/s, Avg generation throughput: 50.6 tokens/s, Running: 1 reqs, Waiting: 0 reqs, GPU KV cache usage: 2.9%, Prefix cache hit rate: 0.0%
(APIServer pid=1) INFO 05-04 17:10:09 [metrics.py:101] SpecDecoding metrics: Mean acceptance length: 2.35, Accepted throughput: 2.09 tokens/s, Drafted throughput: 4.66 tokens/s, Accepted: 291 tokens, Drafted: 648 tokens, Per-position acceptance rate: 0.713, 0.412, 0.222, Avg Draft acceptance rate: 44.9%
(APIServer pid=1) INFO:     172.20.0.1:34066 - "POST /v1/chat/completions HTTP/1.1" 200 OK
(APIServer pid=1) INFO 05-04 17:10:19 [loggers.py:271] Engine 000: Avg prompt throughput: 25.3 tokens/s, Avg generation throughput: 24.9 tokens/s, Running: 0 reqs, Waiting: 0 reqs, GPU KV cache usage: 0.0%, Prefix cache hit rate: 0.0%
(APIServer pid=1) INFO 05-04 17:10:19 [metrics.py:101] SpecDecoding metrics: Mean acceptance length: 2.53, Accepted throughput: 15.10 tokens/s, Drafted throughput: 29.70 tokens/s, Accepted: 151 tokens, Drafted: 297 tokens, Per-position acceptance rate: 0.727, 0.515, 0.283, Avg Draft acceptance rate: 50.8%
(APIServer pid=1) INFO 05-04 17:10:27 [loggers.py:271] Engine 000: Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Waiting: 0 reqs, GPU KV cache usage: 0.0%, Prefix cache hit rate: 0.0%
(APIServer pid=1) INFO 05-04 17:10:37 [loggers.py:271] Engine 000: Avg prompt throughput: 320.7 tokens/s, Avg generation throughput: 21.3 tokens/s, Running: 1 reqs, Waiting: 0 reqs, GPU KV cache usage: 3.6%, Prefix cache hit rate: 17.4%
(APIServer pid=1) INFO 05-04 17:10:37 [metrics.py:101] SpecDecoding metrics: Mean acceptance length: 3.66, Accepted throughput: 7.70 tokens/s, Drafted throughput: 8.70 tokens/s, Accepted: 154 tokens, Drafted: 174 tokens, Per-position acceptance rate: 0.914, 0.914, 0.828, Avg Draft acceptance rate: 88.5%
(APIServer pid=1) INFO:     172.20.0.1:55882 - "POST /v1/chat/completions HTTP/1.1" 200 OK
(APIServer pid=1) INFO 05-04 17:10:47 [loggers.py:271] Engine 000: Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 53.3 tokens/s, Running: 0 reqs, Waiting: 0 reqs, GPU KV cache usage: 0.0%, Prefix cache hit rate: 17.4%
(APIServer pid=1) INFO 05-04 17:10:47 [metrics.py:101] SpecDecoding metrics: Mean acceptance length: 3.96, Accepted throughput: 40.00 tokens/s, Drafted throughput: 40.50 tokens/s, Accepted: 400 tokens, Drafted: 405 tokens, Per-position acceptance rate: 1.000, 0.985, 0.978, Avg Draft acceptance rate: 98.8%
(APIServer pid=1) INFO 05-04 17:10:55 [loggers.py:271] Engine 000: Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Waiting: 0 reqs, GPU KV cache usage: 0.0%, Prefix cache hit rate: 17.4%
(APIServer pid=1) INFO:     172.20.0.1:49140 - "POST /v1/chat/completions HTTP/1.1" 200 OK
(APIServer pid=1) INFO 05-04 17:11:15 [loggers.py:271] Engine 000: Avg prompt throughput: 112.6 tokens/s, Avg generation throughput: 61.8 tokens/s, Running: 1 reqs, Waiting: 0 reqs, GPU KV cache usage: 3.2%, Prefix cache hit rate: 15.5%
(APIServer pid=1) INFO 05-04 17:11:15 [metrics.py:101] SpecDecoding metrics: Mean acceptance length: 3.12, Accepted throughput: 13.97 tokens/s, Drafted throughput: 19.80 tokens/s, Accepted: 419 tokens, Drafted: 594 tokens, Per-position acceptance rate: 0.859, 0.697, 0.561, Avg Draft acceptance rate: 70.5%
(APIServer pid=1) INFO 05-04 17:11:23 [loggers.py:271] Engine 000: Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 43.6 tokens/s, Running: 1 reqs, Waiting: 0 reqs, GPU KV cache usage: 3.2%, Prefix cache hit rate: 15.5%
(APIServer pid=1) INFO 05-04 17:11:23 [metrics.py:101] SpecDecoding metrics: Mean acceptance length: 2.05, Accepted throughput: 22.30 tokens/s, Drafted throughput: 63.90 tokens/s, Accepted: 223 tokens, Drafted: 639 tokens, Per-position acceptance rate: 0.634, 0.305, 0.108, Avg Draft acceptance rate: 34.9%
(APIServer pid=1) INFO 05-04 17:11:33 [loggers.py:271] Engine 000: Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 54.5 tokens/s, Running: 1 reqs, Waiting: 0 reqs, GPU KV cache usage: 3.2%, Prefix cache hit rate: 15.5%
(APIServer pid=1) INFO 05-04 17:11:33 [metrics.py:101] SpecDecoding metrics: Mean acceptance length: 2.57, Accepted throughput: 33.30 tokens/s, Drafted throughput: 63.59 tokens/s, Accepted: 333 tokens, Drafted: 636 tokens, Per-position acceptance rate: 0.755, 0.486, 0.330, Avg Draft acceptance rate: 52.4%
(APIServer pid=1) INFO 05-04 17:11:43 [loggers.py:271] Engine 000: Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 65.2 tokens/s, Running: 1 reqs, Waiting: 0 reqs, GPU KV cache usage: 3.4%, Prefix cache hit rate: 15.5%
(APIServer pid=1) INFO 05-04 17:11:43 [metrics.py:101] SpecDecoding metrics: Mean acceptance length: 3.12, Accepted throughput: 44.30 tokens/s, Drafted throughput: 62.70 tokens/s, Accepted: 443 tokens, Drafted: 627 tokens, Per-position acceptance rate: 0.847, 0.699, 0.574, Avg Draft acceptance rate: 70.7%
(APIServer pid=1) INFO 05-04 17:11:51 [loggers.py:271] Engine 000: Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 78.6 tokens/s, Running: 1 reqs, Waiting: 0 reqs, GPU KV cache usage: 3.4%, Prefix cache hit rate: 15.5%
(APIServer pid=1) INFO 05-04 17:11:51 [metrics.py:101] SpecDecoding metrics: Mean acceptance length: 3.73, Accepted throughput: 57.49 tokens/s, Drafted throughput: 63.29 tokens/s, Accepted: 575 tokens, Drafted: 633 tokens, Per-position acceptance rate: 0.967, 0.905, 0.853, Avg Draft acceptance rate: 90.8%


</details>

---

_Generated by `bash scripts/report.sh`. Add `--verify` for verify-full output, `--bench` for canonical TPS bench, `--full` for both. Use `--no-redact` to disable redaction (internal sharing only)._
rossy@Ross-PC:~/club-3090$
```

### Anything else?

[Dockerlog.txt](https://github.com/user-attachments/files/27370056/Dockerlog.txt)

**Comment by noonghunna** [comment]
@RossNE99 — that's a Windows TDR (Timeout Detection and Recovery) reset, not an OOM. WSL2 inherits Windows' GPU timeout policy. Found it in your Dockerlog — `multiproc_executor.py:962`:

```
File "...inductor_cache/cqu7bj5kvqxclzlbnvna3m6ot3xig2najb633ge5fvjcq7zxdi4s.py", line 2482
    buf9 = torch.ops._C.marlin_gemm.default(buf8, None, arg15_1, ..., s18, 17408, 5120, ...)
RuntimeError: CUDA driver error: device not ready
```

Then immediately:

```
RuntimeError: !handles_.at(i) INTERNAL ASSERT FAILED at "CUDACachingAllocator.cpp":427
```

The combination — `cudaErrorNotReady` (CUDA error 600) on a long-running kernel followed by stale-handle assertion — is the classic signature of **WDDM TDR firing**: Windows force-resets the GPU when a kernel exceeds the TDR delay (default 2 seconds), invalidating every CUDA allocation. After that, every PyTorch handle points at memory the driver no longer owns, so the caching allocator asserts.

## Why a 156K prompt triggers it

At your `--max-num-batched-tokens 8192` (default for `dual.yml`), a 156K prompt prefill chunks into ~19 sequential passes. Each pass runs:

- Marlin GEMM for FFN layers (the line that crashed in your trace, 17408×5120 = the FFN intermediate dim)
- DeltaNet GDN forward (state-materialization for the linear-attention layers)
- Standard attention for the 25% of layers that aren't DeltaNet

On a 3090 with WDDM running, **any single kernel taking >2 seconds** triggers TDR. The DeltaNet GDN forward at deep accumulated context is the most likely candidate to hit that — at 156K source it materializes a multi-hundred-MiB state buffer, and on WSL2 with `pin_memory=False` the host-device transfers add latency on top.

This is a **Windows / WSL2 environmental issue**, not a club-3090 bug. None of the Genesis pins or the dual.yml config will fix it — the GPU is being externally reset by the Windows display driver before vLLM can complete the kernel.

## Fix — extend the TDR delay on Windows host

You have three paths. Pick whichever fits your tolerance for messing with the host.

### Option A (recommended): extend TDR delay to 60 seconds

On the **Windows host** (not inside WSL), open an Administrator PowerShell:

```powershell
Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\GraphicsDrivers" `
  -Name TdrDelay -Type DWord -Value 60 -Force

Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\GraphicsDrivers" `
  -Name TdrDdiDelay -Type DWord -Value 60 -Force
```

Then **reboot Windows** (the registry change only takes effect on boot). After reboot, retry your 156K prompt.

This gives kernels up to 60 seconds before TDR triggers — enough headroom for any single op in a 156K prefill.

### Option B: disable TDR entirely (more permissive, more risk)

If 60 seconds still isn't enough, you can disable TDR:

```powershell
Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\GraphicsDrivers" `
  -Name TdrLevel -Type DWord -Value 0 -Force
```

Then reboot. **Trade-off**: if a kernel actually does hang (driver bug, hardware fault), Windows won't recover the GPU automatically — you may need to hard-reboot. For a dedicated AI rig where the GPUs aren't your display adapters, this is usually fine. For a workstation where one of these 3090s drives your monitor, less ideal.

### Option C: dual-boot Linux (no TDR at all)

Linux doesn't have WDDM TDR — kernel timeout policy is per-driver and much more permissive by default. If you're hitting Windows-specific issues regularly, a bare-metal Ubuntu install gets you out of this whole class. ~Couple hours of setup but every cross-rig benchmark we have is on bare-metal Linux for exactly this reason.

## Verifying the fix worked

After option A or B + reboot, retry the 156K prompt. Watch:

```bash
docker logs vllm-qwen36-27b-dual 2>&1 | grep -iE "device not ready|cuda.*error|timeout"
```

If silent (no matches) and you get a 200 OK response back to Kilo Code, TDR was the cause and it's fixed. If still crashing, paste the new Dockerlog and we'll dig further — but TDR is the strongest candidate given the trace.

## On the boot config itself

The boot log otherwise looks healthy:
- KV cache sized at 176K tokens (concurrency 2.47x for 262K) — should fit a 156K prompt
- vLLM 0.20.1rc1.dev16+g7a1eb8ac2 + Genesis v7.69 (`2db18df`) — current pin
- Loaded clean, MTP working, smaller prompts succeeded with ~50-65 TPS decode

So the engine itself is fine; it just needs more clock-time for the long prefill than Windows is willing to give it before resetting.

(Aside: if TDR fix lands you, would be useful to file a `numbers-from-your-rig` template afterwards — WSL2 + 156K prompt is a hardware/environment combo we don't have data on, and your decode-side TPS would be a useful benchmark point for other Windows users.)

## Adding to docs

I'll add a "Note for WSL2 / Windows users" section to `docs/HARDWARE.md` covering the TDR diagnosis + registry fix so the next person hitting this lands on the answer faster. Will reference your issue.

**Comment by RossNE99** [comment]
Thanks for your suggestions, 

I tried option A, rebooted and hit the same error, then i tried option B, rebooted and i beleve i hit the same error again.

I will attach the latest docker output

[Dockerlog.txt](https://github.com/user-attachments/files/27372860/Dockerlog.txt)


Once we get this ironed out I'll happily share my numbers :)

**Comment by RossNE99** [comment]
Also just to add i just tried to run the scripts/bench.sh and i got the same error when trying to run CODE - measured - run-5

Here are my numbers so far 

rossy@Ross-PC:~/club-3090$ ./scripts/bench.sh

========== NARRATIVE (prompt=65 chars, max_tokens=1000) ==========
=== warmups (3) ===
  warm-1     wall= 15.96s  ttft=   923ms  toks=1000  wall_TPS= 62.66  decode_TPS= 66.51
  warm-2     wall= 17.71s  ttft=   178ms  toks=1000  wall_TPS= 56.47  decode_TPS= 57.04
  warm-3     wall= 15.42s  ttft=   159ms  toks=1000  wall_TPS= 64.86  decode_TPS= 65.54

=== measured (5) ===
  run-1      wall= 17.18s  ttft=   125ms  toks=1000  wall_TPS= 58.21  decode_TPS= 58.64
  run-2      wall= 15.85s  ttft=   160ms  toks=1000  wall_TPS= 63.10  decode_TPS= 63.75
  run-3      wall= 15.54s  ttft=   154ms  toks= 992  wall_TPS= 63.82  decode_TPS= 64.46
  run-4      wall= 17.62s  ttft=   191ms  toks=1000  wall_TPS= 56.76  decode_TPS= 57.38
  run-5      wall= 19.78s  ttft=   229ms  toks=1000  wall_TPS= 50.55  decode_TPS= 51.14

=== summary [narrative] (n=5) ===
  wall_TPS       mean=  58.49   std=  5.38   CV= 9.2%   min=50.55   max=63.82
  decode_TPS     mean=  59.07   std=  5.40   CV= 9.1%   min=51.14   max=64.46
  TTFT          mean=   172ms  std=   40ms  min=125ms  max=229ms

========== CODE (prompt=78 chars, max_tokens=800) ==========
=== warmups (3) ===
  warm-1     wall=  9.70s  ttft=   168ms  toks= 749  wall_TPS= 77.20  decode_TPS= 78.56
  warm-2     wall=  7.28s  ttft=   178ms  toks= 709  wall_TPS= 97.39  decode_TPS= 99.82
  warm-3     wall=  8.45s  ttft=   172ms  toks= 641  wall_TPS= 75.89  decode_TPS= 77.47

=== measured (5) ===
  run-1      wall= 12.07s  ttft=   189ms  toks= 800  wall_TPS= 66.30  decode_TPS= 67.36
  run-2      wall=  8.64s  ttft=   195ms  toks= 670  wall_TPS= 77.57  decode_TPS= 79.37
  run-3      wall= 12.45s  ttft=   169ms  toks= 736  wall_TPS= 59.13  decode_TPS= 59.94
  run-4      wall=  7.57s  ttft=   161ms  toks= 451  wall_TPS= 59.57  decode_TPS= 60.87
^CTraceback (most recent call last):
  File "<stdin>", line 95, in <module>
  File "<stdin>", line 79, in run_set
  File "<stdin>", line 25, in run_once
  File "/usr/lib/python3.12/http/client.py", line 706, in readline
    return super().readline(limit)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 698, in peek
    return self._peek_chunked(n)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 736, in _peek_chunked
    chunk_left = self._get_chunk_left()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 584, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 544, in _read_next_chunk_size
    line = self.fp.readline(_MAXLINE + 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 707, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

rossy@Ross-PC:~/club-3090$




Also here is the docker logs from the crash that occurred during the benchmark 

[BenchDockerlog.txt](https://github.com/user-attachments/files/27373214/BenchDockerlog.txt)

**Comment by noonghunna** [comment]
@RossNE99 — same diagnosis class but worth confirming the registry edits actually took effect, because the symptom is identical.

## What both new logs show

Both crashes have the same signature:
- `RuntimeError: CUDA driver error: device not ready` during a `torch.empty()` / `torch.empty_like()` call inside the GDN forward kernel chain (different specific call site each time, same root cause)
- Followed by `RuntimeError: !handles_.at(i) INTERNAL ASSERT FAILED at "CUDACachingAllocator.cpp":427` — the stale-handle assertion that fires after the device is reset

Critical detail from your bench-crash log (right before the freeze):

```
SpecDecoding metrics: Mean acceptance length: 3.39,
Per-position acceptance rate: 0.921, 0.810, 0.659, Avg Draft acceptance rate: 79.6%
```

**Your MTP is working great** — AL 3.39, 92% first-token accept, matches Lorbus baseline within a couple percent. The infrastructure is solid; the GPU is being externally reset out from under it.

That + the `No available shared memory broadcast block found in 60 seconds` line that follows is the engine-frozen signature: workers waiting on CUDA memory that the driver no longer owns after a TDR reset.

## Worth verifying first — did the registry edit persist?

WSL2 occasionally won't pick up TDR registry changes if Windows wasn't rebooted (not just WSL restarted), or if Group Policy / Windows Update overwrites them on a service restart. Confirm from an **Admin PowerShell**:

```powershell
Get-ItemProperty HKLM:\System\CurrentControlSet\Control\GraphicsDrivers | `
  Select-Object TdrDelay, TdrDdiDelay, TdrLevel
```

You should see something like:
```
TdrDelay   : 60
TdrDdiDelay: 60
TdrLevel   : 0   (if you tried option B)
```

If any of those are missing or showing the original value (TdrDelay=2), the registry didn't actually take. Sometimes Windows Defender's Tamper Protection blocks edits to `GraphicsDrivers` — check **Windows Security → Virus & threat protection settings → Manage settings → Tamper Protection**, turn off, retry the registry edit, reboot, turn Tamper Protection back on.

## If the registry IS set correctly and it's still firing

Two things to try, ordered by likelihood:

### 1. Try `--enforce-eager` to bypass torch.compile

Add to your compose command:
```yaml
- --enforce-eager
```

This skips torch.compile / cudagraph capture, which has the side-effect of changing how kernels are dispatched. Sometimes WSL2's WDDM driver handles eager-mode CUDA calls better than compiled cudagraph blocks (the cudagraphs hold device pointers across frame boundaries, which TDR resets between).

Trade: ~10-15% TPS hit vs compiled mode. But if it makes the difference between a crashing and a working stack, it's worth it on WSL2.

### 2. Increase WSL2 host RAM allocation

Your rig has **16 GB host RAM**, with `RAM: 15Gi total, 13Gi available` reported inside WSL2. Your boot log shows:

```
Auto-prefetch is disabled because the filesystem (EXT4) is not a recognized
network FS (NFS/Lustre) and the checkpoint size (17.69 GiB) exceeds 90% of
available RAM (8.53 GiB).
```

vLLM is paging the 17 GB checkpoint through 8.5 GB of available RAM, which adds latency and creates host-side memory pressure that compounds with GPU kernel timing. WSL2 ALSO inherits WDDM behavior under host memory pressure — kernels can stall waiting on host-mapped memory and trip TDR even when the GPU itself has VRAM headroom.

Edit `C:\Users\<you>\.wslconfig` (Windows host, not inside WSL):
```ini
[wsl2]
memory=24GB
swap=8GB
```

Restart WSL: `wsl --shutdown` then re-open your distro. You should see `RAM: 24Gi total` inside WSL on next boot. With 24 GB host RAM, vLLM should auto-prefetch the checkpoint and host-side latency drops materially.

### 3. (Last resort) bare-metal Linux dual-boot

Per Codex's commentary on this stack: every cross-rig benchmark we have is on bare-metal Linux for exactly the WSL2 TDR class of issues. If 1+2 don't get you stable, dual-boot Ubuntu is the deterministic option.

## Your numbers so far (when it ran)

| | Your WSL2 result | Lorbus baseline (bare-metal 2× 3090) |
|---|---|---|
| Narrative wall TPS | 58.49 (CV 9.2%) | ~69 (CV 2.3%) |
| Code wall TPS | partial (crashed) | ~89 |
| MTP AL | **3.39** ✓ | 3.4-3.8 |
| TTFT | 172 ms | ~85 ms |

Once the TDR / RAM issue is settled, you should land close to Lorbus baseline since your MTP path is healthy. The Narrative gap (~58 vs 69) likely closes most of the way with proper RAM + eager-mode if torch.compile is part of the trigger.

Will add the WSL2 + RAM-pressure note to `docs/HARDWARE.md` once we confirm what works for you.

**Comment by RossNE99** [comment]
Thanks for the detailed insights 


Get-ItemProperty HKLM:\System\CurrentControlSet\Control\GraphicsDrivers | `
  Select-Object TdrDelay, TdrDdiDelay, TdrLevel

Outputs 

TdrDelay TdrDdiDelay TdrLevel
-------- ----------- --------
      60          60        0


Whenever I try to add 

[wsl2]
memory=24GB
swap=8GB

To the WSL config i get the error from my previous issue #32 

so i reverted to my working wsl config (removed ram settings, default of 16 GB and 4 GB swap)

and tried to run the container with --enforce-eager


Which allowed the container to boot, but I got a slightly different error this time when i tried to run the prompt 

[enforce-eagerDockerLog.txt](https://github.com/user-attachments/files/27375842/enforce-eagerDockerLog.txt)

**Comment by noonghunna** [comment]
@RossNE99 — registry settings are correct (`TdrDelay: 60, TdrDdiDelay: 60, TdrLevel: 0`), and `--enforce-eager` did its job — **TDR is no longer firing**. The new error is a different problem class.

## What changed

**Before** (no `--enforce-eager`):
```
RuntimeError: CUDA driver error: device not ready
+ CUDACachingAllocator stale-handle assert
```

**After** (`--enforce-eager`):
```
File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/fla/ops/fused_gdn_prefill_post_conv.py", line 200
    k = torch.empty(L, H, K, dtype=dtype, device=device)
RuntimeError: CUDA driver error: out of memory
```

Different signature: this is honest **OOM** at the DeltaNet GDN forward kernel allocating its state buffer (`k = torch.empty(L, H, K, ...)`), not a kernel reset. The stack is no longer being externally killed — it's now hitting Cliff 2 (the per-card activation-memory ceiling at long prefill).

## Why 156K is at the limit on your config

Per [`docs/CLIFFS.md`](https://github.com/noonghunna/club-3090/blob/master/docs/CLIFFS.md): single-card 24 GB hits Cliff 2 (DeltaNet GDN forward state OOM) around 50-60K prefill. On TP=2 the state splits across cards, so the wall doubles to ~120K. **Your 156K is over that wall.**

`dual.yml` on healthy 24 GB / 3090 baseline can handle up to ~120K cleanly; above that it'd hit the same OOM. Your hitting it at 156K is consistent with the hardware-class limit, not specific to WSL2.

## What's left to make this work

Three options ordered by effort:

### Option A (easiest) — switch to `llamacpp/default` for prompts >120K

```bash
bash scripts/switch.sh llamacpp/default
```

Different engine, no DeltaNet GDN forward kernel to OOM on. ~21 TPS decode (slow vs vLLM's 60 TPS), but cliff-immune at any context length up to 262K. This is the canonical recommendation for >120K single-shot prompts on our stack — see [`docs/SINGLE_CARD.md`](https://github.com/noonghunna/club-3090/blob/master/docs/SINGLE_CARD.md). Trade speed for capacity.

### Option B — chunk the prompt + use `dual.yml` (no `--enforce-eager`)

If you don't actually need 156K in a single shot, split into chunks ≤120K and hit them sequentially. dual.yml without `--enforce-eager` is faster than llama.cpp for the chunks that fit. Architectural workaround; depends on whether your workload (Kilo Code) lets you split.

### Option C — fix the WSL2 RAM blocker first, then retry

You said adding `[wsl2] memory=24GB swap=8GB` triggers your earlier issue #32. That's a separate WSL2-side issue worth resolving — paging the 17 GB checkpoint through 8.5 GB host RAM creates compound pressure that makes Cliff 2 hit earlier than on a healthy host. Even if 156K still doesn't fit in pure VRAM math, more host RAM = lower latency on bookkeeping ops = less likely to compound with TDR/OOM.

What's the error you hit when you add `memory=24GB` to `.wslconfig`? That's tractable to diagnose separately if you want — link to your #32 thread for context.

## What we learned

- **TDR fix worked** (cudaErrorNotReady → no longer fires). Registry persistence confirmed correct.
- **`--enforce-eager` revealed the underlying VRAM ceiling** — Cliff 2 at ~120K on TP=2 / 24 GB. This is a hardware/architectural limit, not a config bug.
- **Your 156K request exceeds the dual-card vLLM ceiling** for this model class. llama.cpp is the deterministic fallback.

## One MTP datapoint worth highlighting

In your earlier `--enforce-eager` boot log, right before the OOM, the SpecDecoding metrics showed `Mean acceptance length: 3.39, Per-position: 0.921, 0.810, 0.659, Avg accept: 79.6%`. **Your MTP is matching Lorbus baseline.** The infrastructure is healthy; the only thing biting you is the long-prompt VRAM ceiling.

For prompts ≤100K on dual.yml (no `--enforce-eager`, no registry hacks beyond what you have), expect ~60-70 narr / ~85-95 code TPS at MTP AL ~3.4. Your bench data so far is consistent with this — the 58/97 numbers you got on partial bench runs match the expected curve once we exclude the crashing 156K case.

**Comment by RossNE99** [comment]
Unfortunately Last night one of my 3090s experienced a catastrophic hardware malfunction so I think this error was caused by failing hardware. 

Rip my 3090 it wss a good card, looks like I'll be running the single card version for now until I can source another card

**Comment by noonghunna** [comment]
@RossNE99 — really sorry about the card 😞 Catastrophic 3090 failure is brutal, especially mid-debug. RIP indeed.

Your diagnosis matches the symptom shape — a dying GPU often surfaces first as `cudaErrorNotReady` or `device not ready` errors under heavy load before failing outright, because the failing memory subsystem can't service prefill bandwidth at long context. The fact that the error reproduced consistently on big prompts (157K) before the catastrophic failure is the signal in retrospect.

## Single-card path is solid in the meantime

For the workload class you were using (Kilo Code at ~150K prompt) on single 3090, our cliff-immune recommendation is:

```bash
bash scripts/switch.sh llamacpp/default
```

Different engine (llama.cpp via Q3_K_XL GGUF), full **262K context** ceiling, no Cliff 1 / Cliff 2 issues that bit you on the dual setup. Slower decode (~21 TPS vs 70+ on dual vLLM) but predictable across the full context range — exactly the regime where Kilo's 150K prompts live.

If you're sourcing a replacement card and want guidance on what to look for, [docs/HARDWARE.md](https://github.com/noonghunna/club-3090/blob/master/docs/HARDWARE.md) has the rundown of compatible hardware classes (3090 / 3090 Ti / 4090 / A6000 all work; Blackwell 5090 has cross-rig data via @apnar on [disc #51](https://github.com/noonghunna/club-3090/discussions/51) if you're considering current-gen).

Closing this issue — the original CUDA error was hardware, not a stack bug. Reopen if you ever sort out a replacement and the same shape recurs on healthy hardware.

**Comment by noonghunna** [comment]
Hardware failure self-diagnosed by OP — closing. Fresh issue welcome if the same shape recurs on healthy hardware.
